medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: medical_user
      password: nabi25
      port: 5432
      dbname: medical_warehouse
      schema: raw
      threads: 1
