version: 2
sources:
  - name: raw
    schema: raw
    tables:
      - name: telegram_messages
      - name: yolo_detections
models:
  - name: stg_telegram_messages
    description: "Staging model for cleaned Telegram messages."
    columns:
      - name: message_id
        description: "Unique identifier for each message."
        tests:
          - not_null
      - name: channel_name
        description: "Name of the Telegram channel."
        tests:
          - not_null
      - name: message_date
        description: "Timestamp of the message."
        tests:
          - not_null
      - name: valid_message
        description: "True if message text is present and non-empty."
      - name: has_image
        description: "True if message contains an image."
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - channel_name
            - message_id
